# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/dell/Desktop/projects/20cred/FFTaccelerator/FFTproject/FFTproject.srcs/sources_1/ip/Wstage1/Wstage1.xci
# IP: The module: 'Wstage1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/dell/Desktop/projects/20cred/FFTaccelerator/FFTproject/FFTproject.gen/sources_1/ip/Wstage1/Wstage1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Wstage1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/dell/Desktop/projects/20cred/FFTaccelerator/FFTproject/FFTproject.srcs/sources_1/ip/Wstage1/Wstage1.xci
# IP: The module: 'Wstage1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/dell/Desktop/projects/20cred/FFTaccelerator/FFTproject/FFTproject.gen/sources_1/ip/Wstage1/Wstage1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Wstage1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
